### PR TITLE
Drug Central Data

### PR DESCRIPTION
**Pull request by tnnrklc**

### CODE REVIEW

**Comment by slobentanzer** [comment]
Could we agree to use google-style (Napoleon) documentation (https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)? If we use different styles, we will not be able to use autodoc. @deeenes

**Comment by slobentanzer** [comment]
@tnnrklc why did you close it?

**Comment by tnnrklc** [comment]
This is my first time doing a pull request i did it by mistake sorry.

**Comment by slobentanzer** [comment]
That's alright, thanks for the modification :)

**Pull request merged**
