### PR TITLE
DrugBank + ChEMBL + HPO Data

### PR DESCRIPTION
**Pull request by tnnrklc**

### CODE REVIEW

**Comment by deeenes** [comment]
Hi Tennur,

Many thanks for the PR! Before merging, could you pls check if the refactored versions all work fine, we don't lose data that we should keep, and everything is processed correctly? DrugBank I couldn't test, I have no access (yes, a database under CC-BY-NC license, haha).

Best,

Denes

**Comment by tnnrklc** [comment]
Hi Denes, @deeenes 

I started testing drugbank but I had some errors. I am working on them I will commit them as I figure it out. Thank you.

**Comment by deeenes** [comment]
Hi Tennur @tnnrklc ,

Thanks for the updates, please let me know if everything here looks alright and I can merge. Or feel free to merge it yourself.

Best,

Denes

**Comment by tnnrklc** [comment]
Hi Denes, @deeenes 

I still need to look at a few things, but I will let you know as soon as I can.

Thank you,

Tennur.

**Comment by tnnrklc** [comment]
Hi Denes, @deeenes 

I have checked the new versions. I needed to make some changes but they all work fine now and there is no data lost. 

Thank you.

**Pull request merged**
